### ISSUE TITLE
Release isik2-terminplanung 1.3.0 contains isik 3 assets

### ISSUE THREAD

**Issue by RobertC-13** [gematik/app-referencevalidator-plugins#14]
Hi,

I was trying to use isik2-terminplanung 1.3.0 only to realize its contains the isik3-terminplanung-0.3.0.zip instead of the isik2 assets.

**Comment by alexey-tschudnowsky** [comment]
Dear @RobertC-13 ,
thanks for the report. We apologize for the wrong plugin attachment. You can find the isik2-terminplanung 1.3.0 plugin on the updated release page (https://github.com/gematik/app-referencevalidator-plugins/releases/tag/isik2-terminplanung-1.3.0) 
Best regards,
Alexey
