### ISSUE TITLE
ValueSet https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_ICD_SEITENLOKALISATION not found by validator

### ISSUE THREAD

**Issue by Pepe-Juarez** [gematik/app-referencevalidator-plugins#6]
We use the app-referencevalidator (https://github.com/gematik/app-referencevalidator) to validate our FHIR resources according to ISiK1 and ISiK2. 
We are trying to use it to validate a Procedure resource that includes the ExtensionSeitenlokalisation extension, the validator raises the following error:
![image](https://github.com/gematik/app-referencevalidator-plugins/assets/158566397/8150fa09-5645-4926-b050-455517e804d2)
We think we are adding the extension correctly according the specifications https://simplifier.net/guide/implementierungsleitfadenisik-basismodul/ImplementationGuide-markdown-Datenobjekte-Datenobjekte-Prozedur?version=current , but maybe we aren't used correctly. You can check the file we use here:
[test-ISIK_Procedure.json](https://github.com/gematik/app-referencevalidator-plugins/files/14138581/test-ISIK_Procedure.json)

We would like to know if there is an error in the reference validator in the ISiK 2 plugin when it checks the ExtensionSeitenlokalisation extension in the Procedure resource.

**Comment by alexey-tschudnowsky** [comment]
Hello @Pepe-Juarez ,

we have published new releases of the plugins with the issue fixed:
- https://github.com/gematik/app-referencevalidator-plugins/releases/tag/isik1-2.0.0
- https://github.com/gematik/app-referencevalidator-plugins/releases/tag/isik2-basismodul-2.0.0
- https://github.com/gematik/app-referencevalidator-plugins/releases/tag/isik3-basismodul-0.3.0

Please let us know, if the fix has worked for you.

Best regards,
Alexey

**Comment by Pepe-Juarez** [comment]
> Hello @Pepe-Juarez ,
> 
> we have published new releases of the plugins with the issue fixed:
> 
> * https://github.com/gematik/app-referencevalidator-plugins/releases/tag/isik1-2.0.0
> * https://github.com/gematik/app-referencevalidator-plugins/releases/tag/isik2-basismodul-2.0.0
> * https://github.com/gematik/app-referencevalidator-plugins/releases/tag/isik3-basismodul-0.3.0
> 
> Please let us know, if the fix has worked for you.
> 
> Best regards, Alexey

Hi @alexey-tschudnowsky , 
   I have tested it, and it works fine. 
Thank you very much!
Pepe Juárez.
